### ISSUE TITLE
installation issues

### ISSUE THREAD

**Issue by baladurzgate** [manuq/stopmo_preview#3]
Hi Manuq !
first thank you for developping this amasing plugin , the youtube video show just what i needed. 
But ! Being a quite young linux user , i fail to install the plugin . It seems like entangle is not finding the right lib or something , here is the log : 

> Traceback (most recent call last):
>   File "<frozen importlib._bootstrap>", line 2158, in _find_spec
> AttributeError: 'DynamicImporter' object has no attribute 'find_spec'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/home/user_name/.config/entangle/plugins/stopmo_preview/stopmo_preview.py", line 10, in <module>
>     from gi.repository import Entangle
>   File "/usr/lib/python3/dist-packages/gi/importer.py", line 53, in find_module
>     'introspection typelib not found' % namespace)
> ImportError: cannot import name Entangle, introspection typelib not found
> 
> (entangle:6138): libpeas-WARNING **: Error loading plugin 'stopmo_preview'

is there a solution to this ? 

Alex

**Comment by gregmcgillcedexis** [comment]
also having the same error 16.04.2 lts xubuntu would like to use this plugin

**Comment by manuq** [comment]
Thanks and sorry for the late reply. Nowadays installation should be much easier than going through the command line. Closing in favour of #8
